project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 challenge 1"
            file: content/01_journal/05_Chapter_1_Challege.qmd
          - text: "02 challenge 2"
            file: content/01_journal/06_Challenge_2_ML.qmd
          - text: "03 challenge 3"
            file: content/01_journal/07_chall_3.qmd
          - text: "04 challenge 4"
            file: content/01_journal/08_chall_4.qmd
          
          
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto